FileVersion = 1
Dependencies = {corlib = "*"}

[Project]
Name = "box2d-beef"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\box2dDebug.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\box2dRelease.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\box2dRelease.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\box2dRelease.lib"]

[Configs.Debug.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libbox2dDebug.a"]

[Configs.Release.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libbox2dRelease.a"]

[Configs.Paranoid.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libbox2dRelease.a"]

[Configs.Test.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx-x64\\bin\\libbox2dRelease.a"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libbox2dDebug.a"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libbox2dRelease.a"]

[Configs.Paranoid.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libbox2dRelease.a"]

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libbox2dRelease.a"]
